### PR TITLE
Hello back

### PR DESCRIPTION
**Pull request by londaploetz**
Created a new branch (Hello-Back)
In the src folder, created a folder components, inside the folder is a mimic of HelloBack.
This pull request needs to be reviewed by Anna.   
Enjoy this picture of a frog. 
download

### CODE REVIEW

**Comment by AnnaxGrace** [comment]
Mmkay, so, the hello back isn't showing up in your browser right? That's because you didn't import the component into App.js. So look at my example, and then import that component into App.js. Then take your code that you have in App.js (the h1) and move it out into a component as well.

Also, when you request a merge request review, it should be reviewed before merged! Generally you ask your lead to review, approve, and then merge. That way it's *their* fault.

You also seem to have a few commits that are the exact same message - it's better to let people know what's been added. It helps the people you work with know what's been changed so they can review. "Updated import line in HelloBack" Generally you want to commit when you have achieved something "HelloBack component is functional", "HelloBack imported into App.js" "Updated HelloBack to include new variables" - these are good examples!

**Comment by londaploetz** [comment]
Also I just realized I can change the names of the commit messages not just the commits so from now on I'll make sure to update the commit names.

**Comment by AnnaxGrace** [comment]
It was closed when I got to it, so I'm not sure what happened.

Maybe call the new component file HelloBitches ?

But basically there shouldn't be any like code code (html or js) in your app.js. Just navigation and importing

**Comment by AnnaxGrace** [comment]
Of course there's always exceptions to rules

**Pull request closed without merging**
